package command

func spec(first, last, step int) KeySpec {
	return KeySpec{First: first, Last: last, Step: step}
}

var table = map[string]Meta{
	// strings
	"GET":         {Name: "GET", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SET":         {Name: "SET", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SETNX":       {Name: "SETNX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SETEX":       {Name: "SETEX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"PSETEX":      {Name: "PSETEX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"GETSET":      {Name: "GETSET", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"GETDEL":      {Name: "GETDEL", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"GETEX":       {Name: "GETEX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"MGET":        {Name: "MGET", Kind: KindRead, Keys: spec(1, -1, 1)},
	"MSET":        {Name: "MSET", Kind: KindWrite, Keys: spec(1, -1, 2)},
	"MSETNX":      {Name: "MSETNX", Kind: KindWrite, Keys: spec(1, -1, 2)},
	"APPEND":      {Name: "APPEND", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"STRLEN":      {Name: "STRLEN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"INCR":        {Name: "INCR", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"DECR":        {Name: "DECR", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"INCRBY":      {Name: "INCRBY", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"DECRBY":      {Name: "DECRBY", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"INCRBYFLOAT": {Name: "INCRBYFLOAT", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"GETRANGE":    {Name: "GETRANGE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SETRANGE":    {Name: "SETRANGE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SETBIT":      {Name: "SETBIT", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"GETBIT":      {Name: "GETBIT", Kind: KindRead, Keys: spec(1, 1, 1)},
	"BITCOUNT":    {Name: "BITCOUNT", Kind: KindRead, Keys: spec(1, 1, 1)},
	"BITPOS":      {Name: "BITPOS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"BITOP":       {Name: "BITOP", Kind: KindWrite, Keys: spec(2, -1, 1)},
	"BITFIELD":    {Name: "BITFIELD", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SUBSTR":      {Name: "SUBSTR", Kind: KindRead, Keys: spec(1, 1, 1)},
	// keys
	"DEL":         {Name: "DEL", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"UNLINK":      {Name: "UNLINK", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"EXISTS":      {Name: "EXISTS", Kind: KindRead, Keys: spec(1, -1, 1)},
	"EXPIRE":      {Name: "EXPIRE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"EXPIREAT":    {Name: "EXPIREAT", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"PEXPIRE":     {Name: "PEXPIRE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"PEXPIREAT":   {Name: "PEXPIREAT", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"TTL":         {Name: "TTL", Kind: KindRead, Keys: spec(1, 1, 1)},
	"PTTL":        {Name: "PTTL", Kind: KindRead, Keys: spec(1, 1, 1)},
	"TYPE":        {Name: "TYPE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"PERSIST":     {Name: "PERSIST", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"RENAME":      {Name: "RENAME", Kind: KindWrite, Keys: spec(1, 2, 1)},
	"RENAMENX":    {Name: "RENAMENX", Kind: KindWrite, Keys: spec(1, 2, 1)},
	"DUMP":        {Name: "DUMP", Kind: KindRead, Keys: spec(1, 1, 1)},
	"RESTORE":     {Name: "RESTORE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"TOUCH":       {Name: "TOUCH", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"COPY":        {Name: "COPY", Kind: KindWrite, Keys: spec(1, 2, 1)},
	"MOVE":        {Name: "MOVE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"OBJECT":      {Name: "OBJECT", Kind: KindRead, Keys: spec(2, 2, 1)},
	"EXPIRETIME":  {Name: "EXPIRETIME", Kind: KindRead, Keys: spec(1, 1, 1)},
	"PEXPIRETIME": {Name: "PEXPIRETIME", Kind: KindRead, Keys: spec(1, 1, 1)},
	// hashes
	"HGET":         {Name: "HGET", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HSET":         {Name: "HSET", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"HSETNX":       {Name: "HSETNX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"HMGET":        {Name: "HMGET", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HMSET":        {Name: "HMSET", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"HDEL":         {Name: "HDEL", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"HEXISTS":      {Name: "HEXISTS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HGETALL":      {Name: "HGETALL", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HINCRBY":      {Name: "HINCRBY", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"HINCRBYFLOAT": {Name: "HINCRBYFLOAT", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"HKEYS":        {Name: "HKEYS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HVALS":        {Name: "HVALS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HLEN":         {Name: "HLEN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HSCAN":        {Name: "HSCAN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HSTRLEN":      {Name: "HSTRLEN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"HRANDFIELD":   {Name: "HRANDFIELD", Kind: KindRead, Keys: spec(1, 1, 1)},
	// lists
	"LPUSH":      {Name: "LPUSH", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"RPUSH":      {Name: "RPUSH", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LPUSHX":     {Name: "LPUSHX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"RPUSHX":     {Name: "RPUSHX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LPOP":       {Name: "LPOP", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"RPOP":       {Name: "RPOP", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LLEN":       {Name: "LLEN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"LINDEX":     {Name: "LINDEX", Kind: KindRead, Keys: spec(1, 1, 1)},
	"LRANGE":     {Name: "LRANGE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"LSET":       {Name: "LSET", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LTRIM":      {Name: "LTRIM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LREM":       {Name: "LREM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LINSERT":    {Name: "LINSERT", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"LMOVE":      {Name: "LMOVE", Kind: KindWrite, Keys: spec(1, 2, 1)},
	"RPOPLPUSH":  {Name: "RPOPLPUSH", Kind: KindWrite, Keys: spec(1, 2, 1)},
	"LMPOP":      {Name: "LMPOP", Kind: KindWrite}, // numkeys special; treat as unknown keys → follow MOVED
	"BLPOP":      {Name: "BLPOP", Kind: KindBlock, Keys: spec(1, -2, 1)},
	"BRPOP":      {Name: "BRPOP", Kind: KindBlock, Keys: spec(1, -2, 1)},
	"BRPOPLPUSH": {Name: "BRPOPLPUSH", Kind: KindBlock, Keys: spec(1, 2, 1)},
	"BLMOVE":     {Name: "BLMOVE", Kind: KindBlock, Keys: spec(1, 2, 1)},
	"BLMPOP":     {Name: "BLMPOP", Kind: KindBlock},
	"LPOS":       {Name: "LPOS", Kind: KindRead, Keys: spec(1, 1, 1)},
	// sets
	"SADD":        {Name: "SADD", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SREM":        {Name: "SREM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SMEMBERS":    {Name: "SMEMBERS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SISMEMBER":   {Name: "SISMEMBER", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SMISMEMBER":  {Name: "SMISMEMBER", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SCARD":       {Name: "SCARD", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SPOP":        {Name: "SPOP", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"SRANDMEMBER": {Name: "SRANDMEMBER", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SMOVE":       {Name: "SMOVE", Kind: KindWrite, Keys: spec(1, 2, 1)},
	"SINTER":      {Name: "SINTER", Kind: KindRead, Keys: spec(1, -1, 1)},
	"SINTERSTORE": {Name: "SINTERSTORE", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"SUNION":      {Name: "SUNION", Kind: KindRead, Keys: spec(1, -1, 1)},
	"SUNIONSTORE": {Name: "SUNIONSTORE", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"SDIFF":       {Name: "SDIFF", Kind: KindRead, Keys: spec(1, -1, 1)},
	"SDIFFSTORE":  {Name: "SDIFFSTORE", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"SSCAN":       {Name: "SSCAN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"SINTERCARD":  {Name: "SINTERCARD", Kind: KindRead},
	// zsets
	"ZADD":             {Name: "ZADD", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZREM":             {Name: "ZREM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZSCORE":           {Name: "ZSCORE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZINCRBY":          {Name: "ZINCRBY", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZCARD":            {Name: "ZCARD", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZCOUNT":           {Name: "ZCOUNT", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZRANGE":           {Name: "ZRANGE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZREVRANGE":        {Name: "ZREVRANGE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZRANGEBYSCORE":    {Name: "ZRANGEBYSCORE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZREVRANGEBYSCORE": {Name: "ZREVRANGEBYSCORE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZRANK":            {Name: "ZRANK", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZREVRANK":         {Name: "ZREVRANK", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZRANGEBYLEX":      {Name: "ZRANGEBYLEX", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZREVRANGEBYLEX":   {Name: "ZREVRANGEBYLEX", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZLEXCOUNT":        {Name: "ZLEXCOUNT", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZREMRANGEBYRANK":  {Name: "ZREMRANGEBYRANK", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZREMRANGEBYSCORE": {Name: "ZREMRANGEBYSCORE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZREMRANGEBYLEX":   {Name: "ZREMRANGEBYLEX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZPOPMIN":          {Name: "ZPOPMIN", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZPOPMAX":          {Name: "ZPOPMAX", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"BZPOPMIN":         {Name: "BZPOPMIN", Kind: KindBlock, Keys: spec(1, -2, 1)},
	"BZPOPMAX":         {Name: "BZPOPMAX", Kind: KindBlock, Keys: spec(1, -2, 1)},
	"BZMPOP":           {Name: "BZMPOP", Kind: KindBlock},
	"ZMPOP":            {Name: "ZMPOP", Kind: KindWrite},
	"ZUNIONSTORE":      {Name: "ZUNIONSTORE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZINTERSTORE":      {Name: "ZINTERSTORE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZDIFFSTORE":       {Name: "ZDIFFSTORE", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"ZUNION":           {Name: "ZUNION", Kind: KindRead},
	"ZINTER":           {Name: "ZINTER", Kind: KindRead},
	"ZDIFF":            {Name: "ZDIFF", Kind: KindRead},
	"ZSCAN":            {Name: "ZSCAN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZMSCORE":          {Name: "ZMSCORE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"ZRANDMEMBER":      {Name: "ZRANDMEMBER", Kind: KindRead, Keys: spec(1, 1, 1)},
	// streams
	"XADD":       {Name: "XADD", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"XLEN":       {Name: "XLEN", Kind: KindRead, Keys: spec(1, 1, 1)},
	"XRANGE":     {Name: "XRANGE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"XREVRANGE":  {Name: "XREVRANGE", Kind: KindRead, Keys: spec(1, 1, 1)},
	"XREAD":      {Name: "XREAD", Kind: KindRead},
	"XREADGROUP": {Name: "XREADGROUP", Kind: KindRead},
	"XACK":       {Name: "XACK", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"XDEL":       {Name: "XDEL", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"XGROUP":     {Name: "XGROUP", Kind: KindWrite, Keys: spec(2, 2, 1)},
	"XINFO":      {Name: "XINFO", Kind: KindRead, Keys: spec(2, 2, 1)},
	"XPENDING":   {Name: "XPENDING", Kind: KindRead, Keys: spec(1, 1, 1)},
	"XCLAIM":     {Name: "XCLAIM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"XAUTOCLAIM": {Name: "XAUTOCLAIM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"XTRIM":      {Name: "XTRIM", Kind: KindWrite, Keys: spec(1, 1, 1)},
	// hyperloglog / geo / misc
	"PFADD":             {Name: "PFADD", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"PFCOUNT":           {Name: "PFCOUNT", Kind: KindRead, Keys: spec(1, -1, 1)},
	"PFMERGE":           {Name: "PFMERGE", Kind: KindWrite, Keys: spec(1, -1, 1)},
	"GEOADD":            {Name: "GEOADD", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"GEODIST":           {Name: "GEODIST", Kind: KindRead, Keys: spec(1, 1, 1)},
	"GEOHASH":           {Name: "GEOHASH", Kind: KindRead, Keys: spec(1, 1, 1)},
	"GEOPOS":            {Name: "GEOPOS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"GEORADIUS":         {Name: "GEORADIUS", Kind: KindRead, Keys: spec(1, 1, 1)},
	"GEORADIUSBYMEMBER": {Name: "GEORADIUSBYMEMBER", Kind: KindRead, Keys: spec(1, 1, 1)},
	"GEOSEARCH":         {Name: "GEOSEARCH", Kind: KindRead, Keys: spec(1, 1, 1)},
	"GEOSEARCHSTORE":    {Name: "GEOSEARCHSTORE", Kind: KindWrite, Keys: spec(1, 2, 1)},
	// scripts
	"EVAL":       {Name: "EVAL", Kind: KindScript},
	"EVALSHA":    {Name: "EVALSHA", Kind: KindScript},
	"EVAL_RO":    {Name: "EVAL_RO", Kind: KindScript},
	"EVALSHA_RO": {Name: "EVALSHA_RO", Kind: KindScript},
	"SCRIPT":     {Name: "SCRIPT", Kind: KindAdmin},
	// txn
	"MULTI":   {Name: "MULTI", Kind: KindTxn},
	"EXEC":    {Name: "EXEC", Kind: KindTxn},
	"DISCARD": {Name: "DISCARD", Kind: KindTxn},
	"WATCH":   {Name: "WATCH", Kind: KindTxn, Keys: spec(1, -1, 1)},
	"UNWATCH": {Name: "UNWATCH", Kind: KindTxn},
	// pubsub
	"PUBLISH":      {Name: "PUBLISH", Kind: KindPubSub},
	"SPUBLISH":     {Name: "SPUBLISH", Kind: KindPubSub},
	"SUBSCRIBE":    {Name: "SUBSCRIBE", Kind: KindPubSub},
	"SSUBSCRIBE":   {Name: "SSUBSCRIBE", Kind: KindPubSub},
	"UNSUBSCRIBE":  {Name: "UNSUBSCRIBE", Kind: KindPubSub},
	"SUNSUBSCRIBE": {Name: "SUNSUBSCRIBE", Kind: KindPubSub},
	"PSUBSCRIBE":   {Name: "PSUBSCRIBE", Kind: KindPubSub},
	"PUNSUBSCRIBE": {Name: "PUNSUBSCRIBE", Kind: KindPubSub},
	"PUBSUB":       {Name: "PUBSUB", Kind: KindPubSub},
	// connection / admin
	"PING":      {Name: "PING", Kind: KindConnection},
	"ECHO":      {Name: "ECHO", Kind: KindConnection},
	"AUTH":      {Name: "AUTH", Kind: KindConnection},
	"QUIT":      {Name: "QUIT", Kind: KindConnection},
	"SELECT":    {Name: "SELECT", Kind: KindConnection},
	"HELLO":     {Name: "HELLO", Kind: KindConnection},
	"CLIENT":    {Name: "CLIENT", Kind: KindConnection},
	"RESET":     {Name: "RESET", Kind: KindConnection},
	"INFO":      {Name: "INFO", Kind: KindAdmin},
	"CLUSTER":   {Name: "CLUSTER", Kind: KindAdmin},
	"COMMAND":   {Name: "COMMAND", Kind: KindAdmin},
	"CONFIG":    {Name: "CONFIG", Kind: KindAdmin},
	"DBSIZE":    {Name: "DBSIZE", Kind: KindAdmin},
	"FLUSHDB":   {Name: "FLUSHDB", Kind: KindAdmin},
	"FLUSHALL":  {Name: "FLUSHALL", Kind: KindAdmin},
	"TIME":      {Name: "TIME", Kind: KindAdmin},
	"READONLY":  {Name: "READONLY", Kind: KindAdmin},
	"READWRITE": {Name: "READWRITE", Kind: KindAdmin},
	"SCAN":      {Name: "SCAN", Kind: KindAdmin},
	"KEYS":      {Name: "KEYS", Kind: KindAdmin},
	"RANDOMKEY": {Name: "RANDOMKEY", Kind: KindAdmin},
	"MEMORY":    {Name: "MEMORY", Kind: KindAdmin},
	"LATENCY":   {Name: "LATENCY", Kind: KindAdmin},
	"ROLE":      {Name: "ROLE", Kind: KindAdmin},
	"LOLWUT":    {Name: "LOLWUT", Kind: KindAdmin},
	"REPLICAOF": {Name: "REPLICAOF", Kind: KindAdmin},
	"SLAVEOF":   {Name: "SLAVEOF", Kind: KindAdmin},
	"WAIT":      {Name: "WAIT", Kind: KindAdmin},
	"JSON.GET":  {Name: "JSON.GET", Kind: KindRead, Keys: spec(1, 1, 1)},
	"JSON.SET":  {Name: "JSON.SET", Kind: KindWrite, Keys: spec(1, 1, 1)},
	"JSON.DEL":  {Name: "JSON.DEL", Kind: KindWrite, Keys: spec(1, 1, 1)},
}
